- hosts: database-servers
  user: root
  roles:
    - common

# start up the first node, bootstrapping a new cluster
- hosts: database-servers[0]
  user: root
  roles:
    - bootstrap
    - sysbench

# start up the other nodes, joining the cluster
- hosts: database-servers[1]:database-servers[2]
  user: root
  roles:
    - nodes
    - sysbench
